site_name: Big Data Analytics
pages:
- Home: 'index.md'
- Getting Started:
  - Overview: 'setup/index.md'
  - Pre-Requisites: 'setup/preliminaries.md'
  - Installation: 'setup/install.md'
- Hands-On:
  - Overview: 'hands-on/index.md'
  - Vagrant: 'hands-on/vagrant.md'
  - Modules, LMod and Easybuild: 'hands-on/easybuild.md'
  - Hadoop/Installation: 'hands-on/hadoop/install.md'
- Contributing:
  - Overview: 'contributing/index.md'
  - Directory Layout: 'layout.md'
  - Repository Setup and Developments: 'contributing/setup.md'
  - Semantic Versioning: 'contributing/versioning.md'
theme: readthedocs
